spring.application.name=Api-Key-demo


# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/api_key_db
spring.datasource.username=mac
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0

spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s


# ===============================
# Server
# ===============================
server.port=8080